### ISSUE TITLE
Need clarification of partonomy in modelling traits and phenotypes

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#156]
Partonomy in modelling traits and phenotypes
============================================

I would like to understand how OBA models traits with regards to partonomy so that we can be consistent when adding new trait patterns.

Some of the [GCIs](https://github.com/obophenotype/bio-attribute-ontology/issues/8) suggest that the partonomic modelling of traits in OBA may be different from how phenotypes are modelled in uPheno.
For example, see GCI in [entity_attribute.yaml](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/dosdp-patterns/entity_attribute.yaml)
 
```yaml
# (Q and characteristic_of some part-of some W) SubClassOf part-of some (Q and characteristic_of-in some W)
# https://github.com/obophenotype/bio-attribute-ontology/issues/8
logical_axioms:
  - axiom_type: GCI
    text: "%s and ('characteristic_of' some ('part_of' some %s)) SubClassOf 'part_of' some (%s and 'characteristic_of' some %s)"
    vars:
      - attribute
      - entity
      - attribute
      - entity
```

How to interpret this GCI, when one trait does not look intuitively part of another, even though there is some partonomic relationship between the bearers?

It makes sense for like a 'duration of M phase' to be part of an 'duration of cell cycle' instance. The 'mass of femur' instance can be part of a 'mass of hindlimb' instance.

However, what if the qualities of the parts are not additive?

For example, the acidity of a 'stomach neuroendocrine cell' intuitively does not seem to be part of the 'acidity of my stomach' even if the cell itself is part of my stomach.
Is the 'shape of my tonsil' is part of the 'shape of my head'?

* * * * * * * * * * * * * * * * * * *

Related issue: https://github.com/obophenotype/bio-attribute-ontology/issues/139#issuecomment-1249920302
