### ISSUE TITLE
Fix obsolete GO component terms

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#204]
There are obsolete GO terms in OBA term components.
I think the effected OBA terms need to be obsoleted with annotations to suggest replacement terms.

1. OBA:1000323
    - [obsolete divalent inorganic cation homeostasis](https://www.ebi.ac.uk/ols/terms?id=GO:0072507) OBSOLETE. Any process involved in the maintenance of an internal steady state of divalent cations within an organism or cell.
        * replaced_by	GO:0055080	Biological Process	monoatomic cation homeostasis
2. OBA:1000455 zinc ion homeostasis --> *NO GO term REPLACEMENT!!* <https://github.com/geneontology/go-ontology/issues/24464>
    - see <https://www.ebi.ac.uk/QuickGO/term/GO:0055069>
        * consider	GO:0006882	Biological Process	intracellular zinc ion homeostasis
        * consider	GO:0180002	Biological Process	renal zinc excretion
3. OBA:1000500 [obsolete monovalent inorganic cation homeostasis](https://www.ebi.ac.uk/QuickGO/term/GO:0055067)
    * replaced_by	GO:0055080	Biological Process	monoatomic cation homeostasis
4. OBA:1000884
    - [obsolete galactose homeostasis](https://www.ebi.ac.uk/QuickGO/term/GO:0033501)
        * consider	GO:0033502	Biological Process	intracellular galactose homeostasis

**Comment by matentzn** [comment]
I would not obsolete any of these perfectly fine OBA terms IMO.. What I did is simply moving these with a text editor into `src/ontology/oba-edit.obo` when there is no replacement.

**Comment by matentzn** [comment]
Big problem with GO atm, and I have complained to them a bit.. Maybe we need to make a bigger issue.

**Comment by rays22** [comment]
@matentzn ,
How about using a new generic entity homeostasis trait pattern for these OBA terms? 

```yaml
classes:
  entity: owl:Thing
  process_quality: PATO:0001236
  homeostatic_process: GO:0042592

relations:
  characteristic_of: RO:0000052
  has_input: RO:0002233


vars:
  entity: "'entity'"

name:
  text: "%s homeostasis"
  vars:
    - entity


def:
  text: "A trait that affects the biological process involved in the
maintenance of an internal steady state of %s."
  vars:
    - entity

equivalentTo:
  text: "'process_quality' and
        ('characteristic_of' some
        ('homeostatic_process' and
        ('has_input' some %s)))"
  vars:
    - entity
```
