### ISSUE TITLE
Add draft patter for bone length from to

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bio-attribute-ontology#73]
suggested pattern for auto-classification under bone length.  Not attempting to devise EquivalentClass def for these as too hard to do that while fulfilling simple classification use case.

```yaml
length pattern:
	var: bone
            var: from
 	var: to
 
logical_axioms: 
   axiom_type: subClassOf
   text: length and 'inheres in' some %s
   vars:
      - bone
   axiom_type: subClassOf
   text: 'inheres in' some (line and 'connected to' some %s)
   vars:
     - from
   axiom_type: subClassOf
   text: 'inheres in' some (line and 'connected to' some %s)
   vars:
     - to
```

Also populate tsv with some examples form FOVT: 

e.g.  
![image](https://user-images.githubusercontent.com/112839/156777410-0e4fe705-618a-4864-af71-791bfd4d7557.png)

**Comment by dosumis** [comment]
TBD - how to integrate with FOVT as terms are created.  SSSOM?  Or dynamic import into FOVT + obsoletion of FOVT term with replaced_by mappings to new OBA terms.  Note - we can add over label, def, xref overrides etc if need to pull more content now in FOVT.

**Comment by matentzn** [comment]
(I would suggest @megbalk to basically do the same in OBA as we do in uPheno: make PRs for new DOSDP patterns one by one, and then incorporate FOVT terms for that pattern with provenance to FUTRES to OBA (using OBA ids). )

**Comment by megbalk** [comment]
I will work off the pull request.

**Comment by megbalk** [comment]
The two subclasses should be (based on General class axioms for "line connecting laterally paired nipples" in OBA):

'part of' some (length and ('characteristic of' some BONE))

length and ('characteristic of' some ('anatomical line' and connects some TO and connects some FROM))

**Comment by matentzn** [comment]
you cannot use `part of` in conjunction with length, only in conjunction with anatomical entities. Do you mean:

length and characteristic of some (part of some BONE)?

**Comment by megbalk** [comment]
I think so, although I am failing to understand the difference between:

length and characteristic of some (part of some BONE) 

length and (characteristic of some BONE)

**Comment by matentzn** [comment]
Very difficult problem for phenotype modelling, and you are not alone in that confusion. The difference between the two is only logical, and not biological. The second (length and (characteristic of some BONE)) means that the attribute (length) pertains to the _whole_ bone. The first (length and characteristic of some (part of some BONE)) means that the attribute/quality length pertains to the whole bone or _any of its parts_. So if you were to have an increase in the length of cell part of the bone, it would be considered an increase in length of the whole bone. That is obviously wrong.

**Comment by megbalk** [comment]
So to clarify:

A) if we have two measurements that are for the entire length of a bone, but measured at different points, we would have "length and (characteristic of some bone)"

B) if we are measuring a part of the bone, like only the distal end, we would have "length and characteristic of some (part of some bone)"

Is that correct?

**Comment by matentzn** [comment]
Yes!

**Comment by megbalk** [comment]
ok, I'll make edits to this file

**Comment by megbalk** [comment]
I am curious if we need two patterns:
1) length and ('characteristic of' some 'bone') e.g., length and ('characteristic of' some humerus)
2) length and ('characteristic of' some ('part of' some 'bone')), e.g., length and ('characteristic of' some ('part of' some ('in distal side of' some humerus)))

**Comment by rays22** [comment]
The FOVT examples I checked imply length qualities along an anatomical *axis* from anatomical entity A to anatomical enity B. The measurement seems to be along a line in the sense of geometry and *not in the sense of* a non-material anatomical boundary such as [UBERON:0006800 anatomical line](https://www.ebi.ac.uk/ols/ontologies/UBERON/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0006800)
* FOVT:0001070 femur length from caput to lateral condyle [The length along the anterior-posterior *axis* of a femur connecting the caput of a femur to the lateral condyle of a femur.](https://www.ebi.ac.uk/ols/ontologies/FOVT/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOVT_0001070)
* FOVT:0001077 length of talus along the midline [The length along the midline of a talus along the proximal-distal *axis* (non-plantigrade) or anterior-posterior axis (plantigrade) from the groove for a flexor hallucis longus tendon of a talus to a head of a talus.](https://www.ebi.ac.uk/ols/ontologies/FOVT/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOVT_0001077)
* FOVT:0000007 femur length from caput to medial condyle [The length of a *line* of a femur from a medial condyle of a femur to a head of a femur.](https://www.ebi.ac.uk/ols/ontologies/FOVT/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOVT_FOVT_0000007)

 I think here the attribute/trait is intended to be a `subClassOf`
* [length](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000122) and (
* [characteristic of](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002314&lang=en&viewMode=All&siblings=false) some (
    * [part of](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002314&lang=en&viewMode=All&siblings=false) some [anatomical entity](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001062&lang=en&viewMode=PreferredRoots&siblings=false) ) )

, which I think is the same as `subClassOf`
* [length](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000122) and (
    * [characteristic of part of](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002314&lang=en&viewMode=All&siblings=false) some [anatomical entity](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001062&lang=en&viewMode=PreferredRoots&siblings=false) )

I guess you want to relate this attribute/trait category explicitly to the two anatomical entities that determine the measurement points (anatomical entities A and B), otherwise we could just use the existing pattern `entity_attribute_part_of`.
I think it is the [position](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000122) of the anatomical entities A and B which represents the relevant trait/attribute here.
I suggest we model this with two additional `subClassOf` logical axioms:
* [position originates from] and (
    * [characteristic of](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002314&lang=en&viewMode=All&siblings=false) some  'ANATOMICAL ENTITY A'
* [position originates from] and (
    * [characteristic of](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002314&lang=en&viewMode=All&siblings=false) some  'ANATOMICAL ENTITY B'

### My proposed model:

```yaml
vars:
    bone: 'anatomical entity'
    from: 'anatomical entity'
    to: 'anatomical entity'
 
logical_axioms: 
   axiom_type: subClassOf
   text: "length and (
        'characteristic of part of' some %s"
   vars:
      - bone
   axiom_type: subClassOf
   text: "'position originates from' and (
        'characteristic of' some %s)"
   vars:
     - from
   axiom_type: subClassOf
   text: "'position originates from' and (
        'characteristic of' some %s)"
   vars:
     - to
```

**Comment by rays22** [comment]
Taking inspiration from uPheno pattern `abnormalDistanceBetweenAnatomicalEntities.yaml`, I have modified my model to:

```yaml
vars:
    bone: 'bone element'
    from: 'anatomical entity'
    to: 'anatomical entity'
 
logical_axioms: 
   axiom_type: subClassOf
   text: "length and (
        'characteristic of part of' some %s"
   vars:
      - bone
   axiom_type: subClassOf
   text: "'position originates from' and (
        'characteristic of' some %s) and (
        'towards' some %s)"
   vars:
     - from
     - to
```
Alternatively, I could use [PATO:0000040 distance](https://www.ebi.ac.uk/ols/ontologies/PATO/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000040) instead of [PATO:0040002 position originates from](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0040002) as one of the qualities in the pattern.
What do you think @matentzn ?
