### ISSUE TITLE
New 'trait in response' pattern involving CHEBI roles

### ISSUE THREAD

**Issue by rays22** [obophenotype/bio-attribute-ontology#96]
## Create a DOSDP pattern related to `response_to_chemical_stimulus_trait.yaml`. 

CHEBI has 'roles' which can help automatic classification of `response to chemical stimulus` patterns, but we need a new pattern to use them.

## Preferred term label

Automatic, based on DOSDP pattern, e.g. `trait in response to coagulant`

## Suggested parent term

```
'process quality'
 and ('inheres in' some 
    ('response to stimulus'
     and ('has input' some ('has role' some anticoagulant))))
```

**Comment by rays22** [comment]
This is fixed in https://github.com/obophenotype/bio-attribute-ontology/pull/99.
* I have chosen a different pattern name from the one above to distinguish this pattern from the existing [response to chemical stimulus trait](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/dosdp-patterns/response_to_chemical_stimulus_trait.yaml) pattern, where the chemical stimulus variable is a chemical entity : [response_to_chemical_with_role_stimulus](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/dosdp-patterns/response_to_chemical_with_role_stimulus.yaml)

``` yaml
equivalentTo:
  text: "'process_quality' and
        ('characteristic_of' some
        ('response_to_stimulus' and
        ('has_input' some
        ('chemical_entity' and ('has_role' some %s)))))"
  vars:
    - role
```
